/*
 * --------------------------------------------------------------------------- *
 * File: data.ts                                                               *
 * Project: website                                                            *
 * Created Date: 24 Jul 2023                                                   *
 * Author: Vikas K Solegaonkar (vikas@solegaonkar.com)                         *
 * Copyright(c) Vikas K Solegaonkar, 2023                                      *
 *                                                                             *
 * Last Modified: Tue Jul 25 2023                                              *
 * Modified By: Vikas K Solegaonkar                                            *
 *                                                                             *
 * HISTORY:                                                                    *
 * --------------------------------------------------------------------------- *
 * Date         By     Comments                                                *
 * --------------------------------------------------------------------------- *
 */

export const Data = {
  books: [
    {
      file: "english_amrutanubhava_today",
      language: "English",
      translator: "Translator: Vasant Joshi",
      author: "Author: Babaji Maharaj Pandit",
      series: "",
      title: "Amrutanubhava Today",
      extendedTitle: "",
      topic: "",
      original: "Amrutanubhav",
    },
    {
      file: "english_blind_leads_unblind",
      language: "English",
      translator: "Translator: D V Pophli",
      author: "Author: Dr Sharad D Kopardekar",
      series: "",
      title: "Blind Leads Unblind",
      extendedTitle: "",
      topic: "Biography",
      original: "Madhuradvaitacharya Gulabrao Maharaj",
    },
    {
      file: "english_ghatate_sages_mission_aryan_hindu_cultures",
      language: "English",
      translator: "Translator: Vasant Joshi",
      author: "Author: Dr Krishna Madhav Ghatate",
      series: "Sage's Mission",
      title: "Aryan Hindu Cultures - Historic versions nd distortions.",
      extendedTitle: "",
      topic: "",
      original: "",
    },
    {
      file: "english_ghatate_the_perfect_harmony",
      language: "English",
      translator: "Translator: Vilas Kale",
      author: "Author: Dr Krishna Madhav Ghatate",
      series: "",
      title: "The Perfect Harmony",
      extendedTitle: "Samanvaya Maharshi Gulabrao Maharaj on Harmonized Coordination of Religions",
      topic: "",
      original: "Sarvadharma Samanvay",
    },
    {
      file: "english_gulabrao_maharaj_biography",
      language: "English",
      translator: "Translator: Vilas Kale",
      author: "",
      series: "",
      title: "Shri Gulabrao Maharaj - A Biography",
      extendedTitle: "A Biography of Shree Gulabrao Maharaj",
      topic: "Biography",
      original: "",
    },
    {
      file: "english_haripatha_rahasya",
      language: "English",
      translator: "Translator: Vasant Joshi",
      author: "Author: Babaji Maharaj Pandit",
      series: "",
      title: "Hari Doctrine Secret",
      extendedTitle: "Commentary on Jnyaneshwara Maharaj's Hari Path Rahasya",
      topic: "Commentary",
      original: "Haripatha Rahasya",
    },
    {
      file: "english_hrim_narayanaaya_namah_hrim",
      language: "English",
      translator: "",
      author: "Author: Dr Ram Pandit",
      series: "",
      title: "Hrim Narayanaya Namah Hrim",
      extendedTitle: "",
      topic: "Biography",
      original: "",
    },
    {
      file: "english_leena_rastogi_philosophy_of_gulabrao_maharaj",
      language: "English",
      translator: "",
      author: "Author: Leena Rastogi",
      series: "",
      title: "Philosophy of Shree Gulabrao Maharaj",
      extendedTitle: "",
      topic: "",
      original: "",
    },
    {
      file: "english_madhuradvaita_darshan",
      language: "English",
      translator: "",
      author: "",
      series: "",
      title: "Madhuradvaita Darshan",
      extendedTitle: "A collection of articles on Madhuradvaita Philosophy",
      topic: "",
      original: "",
    },
    {
      file: "english_manasayurveda",
      language: "English",
      translator: "",
      author: "Author: Dr Avinash Keshav Dorle",
      series: "",
      title: "Manasayurveda",
      extendedTitle: "Notable articles on Samanvay Maharshi: Madhuradvaitacharya Shri Gulabrao Maharaj",
      topic: "",
      original: "",
    },
    {
      file: "english_sages_mission",
      language: "English",
      translator: "Translator: Vasant Joshi",
      author: "",
      series: "",
      title: "Sage's Mission",
      extendedTitle: 'English version of twenty "Gulab Vatika" booklets. Life mission of saint Gulabrao Maharaj',
      topic: "",
      original: "Gulab Vatika (twenty booklets)",
    },
    {
      file: "english_sages_wisdom_sadhubodh",
      language: "English",
      translator: "Translator: Vasant Joshi",
      author: "",
      series: "",
      title: "Sage's Wisdom",
      extendedTitle:
        'English version of twenty "Sadhu Bodh" Question / Answers of Saint Gulabrao Maharaj and His Disciples',
      topic: "",
      original: "Sadhu Bodh",
    },
    {
      file: "english_vnpandit_gulabrao_maharaj",
      language: "English",
      translator: "",
      author: "Author: Dr Vasudev Narayan Pandit",
      series: "",
      title: "Shri Gulabrao Maharaj",
      extendedTitle: "A Biography of Shree Gulabrao Maharaj",
      topic: "Essay",
      original: "",
    },
    {
      file: "english_yoga_prabhava_yoga_sutra",
      language: "English",
      translator: "Translator: Vasant Joshi",
      author: "Author: Shree Gulabrao Maharaj",
      series: "",
      title: "Yoga Prabhava",
      extendedTitle: 'Discourse by Saint Gulabrao Maharaj on "Patanjala Yogasutra"',
      topic: "Discourse",
      original: "Patanjali Yoga Sutra",
    },
    {
      file: "hindi_amrutanubhav_kaumudi",
      language: "Hindi",
      translator: "अनुवादक​: डाँ ह श्री साने",
      author: "लेखक​: बाबाजी महाराज पंडित",
      series: "",
      title: "अमृतानुभव कौमुदि",
      extendedTitle: "अमृतानुभव पर शांकर मतानुसार भक्ति भाष्य",
      topic: "",
      original: "अमृतानुभव",
    },
    {
      file: "hindi_ghatate_vichar_Sampada",
      language: "Hindi",
      translator: "",
      author: "लेखक​: कृष्ण माधव घटाटे",
      series: "",
      title: "विचारसंपदा",
      extendedTitle: "मधुरद्वैताचर्य श्री गुलाबराव महराजकी विचारसंपदा",
      topic: "",
      original: "",
    },
    {
      file: "hindi_haripath_rahasya",
      language: "Hindi",
      translator: "",
      author: "लेखक​: बाबाजी महाराज पंडित",
      series: "",
      title: "हरिपाठ रहस्य",
      extendedTitle: "",
      topic: "",
      original: "हरिपाठ ",
    },
    {
      file: "hindi_jnyaneshwari_goodharthadeepika_1_8",
      language: "Hindi",
      translator: "अनुवादक​: प्रा डाँ विद्या सहस्रबुद्धे",
      author: "लेखक​: बाबाजी महाराज पंडित",
      series: "",
      title: "गूढार्थदीपिका 1-8",
      extendedTitle: "श्री ज्ञानेश्वरी गूढार्थदीपिका अध्याय 1 से 8",
      topic: "Commentary",
      original: "ज्ञानेश्वरी ",
    },
    {
      file: "hindi_jnyaneshwari_goodharthadeepika_9_13",
      language: "Hindi",
      translator: "अनुवादक​: प्रा डाँ विद्या सहस्रबुद्धे",
      author: "लेखक​: बाबाजी महाराज पंडित",
      series: "",
      title: "गूढार्थदीपिका 9-13",
      extendedTitle: "श्री ज्ञानेश्वरी गूढार्थदीपिका अध्याय 9 से 13",
      topic: "Commentary",
      original: "ज्ञानेश्वरी ",
    },
    {
      file: "hindi_jnyaneshwari_goodharthadeepika_14_18",
      language: "Hindi",
      translator: "अनुवादक​: प्रा डाँ विद्या सहस्रबुद्धे",
      author: "लेखक​: बाबाजी महाराज पंडित",
      series: "",
      title: "गूढार्थदीपिका 14-18",
      extendedTitle: "श्री ज्ञानेश्वरी गूढार्थदीपिका अध्याय 14 से 18",
      topic: "Commentary",
      original: "ज्ञानेश्वरी ",
    },
    {
      file: "hindi_manoharini_geeta",
      language: "Hindi",
      translator: "",
      author: "लेखक​: सुन्दर्बाई केकरे",
      series: "",
      title: "मनोहारिणी गीता",
      extendedTitle: "भगवद्गीतासार हिन्दी प्रवचनानि",
      topic: "Commentary",
      original: "भगवद्गीता",
    },
    {
      file: "hindi_pareshpandit_babaji_maharaj_jeevan",
      language: "Hindi",
      translator: "",
      author: "लेखक​: परेश पंडित",
      series: "",
      title: "वेदांतकेसरी श्री बबजी महाराज",
      extendedTitle: "वेदांतकेसरी श्री बबजी महाराज : जीवन दर्शन और साहित्य",
      topic: "Biography",
      original: "",
    },
    {
      file: "hindi_samantavyansha_siddhanta_tushar",
      language: "Hindi",
      translator: "",
      author: "लेखक​: श्री गुलाबराव महाराज ",
      series: "",
      title: "समन्तव्यांशसिद्धन्ततुषार ",
      extendedTitle: "यथा व्रजगोपिकानाम् - सूक्तिरचनावलि ",
      topic: "",
      original: "",
    },
    {
      file: "hindi_sant_jnyaneshwar_bhakti_yatra",
      language: "Hindi",
      translator: "अनुवादक​: प्रा डाँ विद्या सहस्रबुद्धे",
      author: "लेखक​: बाबाजी महाराज पंडित",
      series: "",
      title: "संत ज्ञानेश्वर और भक्तियात्रा",
      extendedTitle: "संतश्रेष्ठ श्री ज्ञानेश्वर महारज के भक्ति दर्शन पर लेख संग्रह ",
      topic: "",
      original: "",
    },
    {
      file: "hindi_vnpandit_bhaktitatvavivek",
      language: "Hindi",
      translator: "अनुवादक​: प्रा डाँ विद्या सहस्रबुद्धे",
      author: "लेखक​: डाँ वा ना पंडित ",
      series: "",
      title: "भक्तितत्वविवेक",
      extendedTitle: "मधुराद्वैताचार्य गुलाबराव महाराज कृत ",
      topic: "",
      original: "",
    },
    {
      file: "hindi_vnpandit_chiranjeev_padabhyasa",
      language: "Hindi",
      translator: "अनुवादक​: डाँ हेमा जावडेकर",
      author: "लेखक​: डाँ वा ना पंडित ",
      series: "",
      title: "चिरंजीवपदाभ्यास ",
      extendedTitle: "संत श्री गुलाबरावमहारज विरचित भक्तिशास्त्र - चिरंजीवपदाभ्यास ",
      topic: "",
      original: "",
    },
    {
      file: "hindi_vnpandit_madhuradvaita_bhashya_rachanavali_1",
      language: "Hindi",
      translator: "",
      author: "लेखक​: डाँ वा ना पंडित ",
      series: "",
      title: "मधुराद्वैत भाष्यरचनावली - १",
      extendedTitle: "मधुराद्वैत भाष्यरचनावली : खंड १ : भगवद्गीता संगति, चिरंजीवपदाभ्यास, संतज्ञानेश्वर भक्तियोग ",
      topic: "Commentary",
      original: "",
    },
    {
      file: "hindi_vnpandit_madhuradvaita_bhashya_rachanavali_2",
      language: "Hindi",
      translator: "",
      author: "लेखक​: डाँ वा ना पंडित ",
      series: "",
      title: "मधुराद्वैत भाष्यरचनावली - २",
      extendedTitle: "मधुराद्वैत भाष्यरचनावली : खंड २ : निधीध्यासन प्रकाश, वेदस्तुती दीपिका ",
      topic: "Commentary",
      original: "",
    },
    {
      file: "hindi_vnpandit_madhuradvaita_bhashya_rachanavali_3",
      language: "Hindi",
      translator: "",
      author: "लेखक​: डाँ वा ना पंडित ",
      series: "",
      title: "मधुराद्वैत भाष्यरचनावली - ३",
      extendedTitle: "मधुराद्वैत भाष्यरचनावली : खंड ३ : भक्तितत्वविवेक प्रिय पाहुणेर ",
      topic: "Commentary",
      original: "",
    },
    {
      file: "hindi_vnpandit_nididhyasan_prakash",
      language: "Hindi",
      translator: "अनुवादक​: डाँ हेमा जावडेकर",
      author: "लेखक​: डाँ वा ना पंडित ",
      series: "",
      title: "निदिध्यासन प्रकाश ",
      extendedTitle: "मधुराद्वैताचार्य गुलाबराव महाराज कृत निदिध्यासन प्रकाश - पराप्रीति के प्रांगण में",
      topic: "Commentary",
      original: "",
    },
    {
      file: "hindi_vnpandit_shankar_darshan_me_bhakti",
      language: "Hindi",
      translator: "अनुवादक​: डाँ हेमा जावडेकर",
      author: "लेखक​: डाँ वा ना पंडित ",
      series: "",
      title: "शांकरदर्शन में भक्तियोग ",
      extendedTitle: "",
      topic: "",
      original: "",
    },
    {
      file: "hindi_vnpandit_shreemad_bhagawad_geeta_sangati",
      language: "Hindi",
      translator: "अनुवादक​: डाँ हेमा जावडेकर",
      author: "लेखक​: डाँ वा ना पंडित ",
      series: "",
      title: "श्रीमद्भगवद्गीता संगति ",
      extendedTitle: "मधुराद्वैताचार्य श्रीगुलाबराव महाराज कृत श्रीमद्भगवद्गीता संगति ",
      topic: "Commentary",
      original: "भगवद्गीता",
    },
    {
      file: "hindi_vnpandit_vedavastu_deepika",
      language: "Hindi",
      translator: "अनुवादक​: डाँ हेमा जावडेकर",
      author: "लेखक​: डाँ वा ना पंडित ",
      series: "",
      title: "वेदवस्तु दीपिका",
      extendedTitle: "",
      topic: "",
      original: "",
    },
    {
      file: "marathi_130_grantha_patra_saransha",
      language: "Marathi",
      translator: "",
      author: "लेखक​: बाबाजी महाराज पंडित",
      series: "",
      title: "ग्रंथांचा व पत्रांचा सारांश ",
      extendedTitle: "महाराजांच्या १३० ग्रंथांचा व ११८ पत्रांचा सारांश ",
      topic: "Essay",
      original: "",
    },
    {
      file: "marathi_130_granthanche_saar",
      language: "Marathi",
      translator: "",
      author: "लेखक​: बाबाजी महाराज पंडित",
      series: "",
      title: "ग्रंथांचा व पत्रांचा सारांश ",
      extendedTitle: "महाराजांच्या १३० ग्रंथांचा व ११८ पत्रांचा सारांश ",
      topic: "Essay",
      original: "",
    },
    {
      file: "marathi_abhanga_gaatha",
      language: "Marathi",
      translator: "",
      author: "लेखक​: बाबाजी महाराज पंडित",
      series: "",
      title: "अभंग गाथा",
      extendedTitle: "वेदांतकेसरी श्री बबजी महाराज कृत अभंग गाथा",
      topic: "",
      original: "",
    },
    {
      file: "marathi_alaukik_vyakhyana_mala",
      language: "Marathi",
      translator: "",
      author: "लेखक​: बाबाजी महाराज पंडित",
      series: "",
      title: "आलौकिक व्याख्यानमाला ",
      extendedTitle:
        'मधुरद्वैताचार्य श्रीगुलाबराव महाराजांची स्वरचित "अंतर्विज्ञानसंहिता" या ग्रंथातील काही सूत्रांवर ९ व्याख्याने ',
      topic: "",
      original: "",
    },
    {
      file: "marathi_anugraha",
      language: "Marathi",
      translator: "",
      author: "लेखक​: बाबाजी महाराज पंडित",
      series: "",
      title: "अनुग्रह",
      extendedTitle: "परमार्थ प्रबोधन दैनन्दिनीं",
      topic: "",
      original: "",
    },
    {
      file: "marathi_arya_dharmopapatti",
      language: "Marathi",
      translator: "",
      author: "लेखक​: बाबाजी महाराज पंडित",
      series: "",
      title: "आर्यधर्मोपपत्ति",
      extendedTitle: "आर्यधर्माची मूलभूत धारणा, युक्ति आणी प्रमाणांनी समजवून सांगणारा ग्रंथ ",
      topic: "",
      original: "",
    },
    {
      file: "marathi_babaji_maharaj_atma_charitra",
      language: "Marathi",
      translator: "",
      author: "लेखक​: बाबाजी महाराज पंडित",
      series: "",
      title: "आत्मचरित्र ",
      extendedTitle: "सद्गुरुनाथ श्री बाबाजीमहाराज पंडितांचे आत्मचित्र ",
      topic: "Biography",
      original: "",
    },
    {
      file: "marathi_bhakti_pada_tirthamruta",
      language: "Marathi",
      translator: "",
      author: "लेखक​: बाबाजी महाराज पंडित",
      series: "",
      title: "भक्तिपदतीर्थामृत ",
      extendedTitle: "श्री ज्ञानदेवांच्या २ व श्री गुलाबराव महाराजंच्या १० ग्रंथांचे केलेले अनुवाद ",
      topic: "Stories",
      original: "",
    },
    {
      file: "marathi_bhakti_tatva_priya_pahuner",
      language: "Marathi",
      translator: "",
      author: "लेखक​: बाबाजी महाराज पंडित",
      series: "",
      title: "भक्तितत्व प्रिय पाहुणेर ",
      extendedTitle: "यष्टी दोन मधील ग्रन्थ ",
      topic: "",
      original: "",
    },
    {
      file: "marathi_chiranjiva_padabhyaasa",
      language: "Marathi",
      translator: "",
      author: "लेखक​: बाबाजी महाराज पंडित",
      series: "",
      title: "भक्तिशास्त्र - चिरंजीवपदाभ्यास ",
      extendedTitle: "मधुराद्वैताचर्य श्री गुलाबराव महाराज कृत ",
      topic: "",
      original: "",
    },
    {
      file: "marathi_chittopadesha",
      language: "Marathi",
      translator: "",
      author: "लेखक​: बाबाजी महाराज पंडित",
      series: "",
      title: "चित्तोपदेश",
      extendedTitle: "श्री ज्ञानदेवांच्या २ व श्री गुलाबराव महाराजंच्या १० ग्रंथांचे केलेले अनुवाद ",
      topic: "Stories",
      original: "",
    },
    {
      file: "marathi_gaana_sopana",
      language: "Marathi",
      translator: "अनुवादक​: डाँ रूपा कुलकर्णी ",
      author: "लेखक​: श्री गुलाबराव महारज",
      series: "",
      title: "गानसोपान",
      extendedTitle: "श्री गुलाबराव महारजांचा संगीत सिद्धन्त समीक्षण व मूळ संहिता ",
      topic: "",
      original: "",
    },
    {
      file: "marathi_ganga_sthiti_nirnaya",
      language: "Marathi",
      translator: "",
      author: "",
      series: "",
      title: "गंगास्थिति निर्णय ",
      extendedTitle: "गंगा महात्म्य सिद्धी, गंगा तीर्थ निर्णय, गंगा तीर्थ निर्णय विस्तार ",
      topic: "Essay",
      original: "",
    },
    {
      file: "marathi_ghatate_gulabrao_maharaj_charitra",
      language: "Marathi",
      translator: "",
      author: "लेखक​: कृष्ण माधव घटाटे",
      series: "",
      title: "गुलाबरावमहाराज यांचे चरित्र",
      extendedTitle: "श्रीज्ञानेश्वरकन्यापदपांसु वर्हाडातील सुप्रसिद्ध सत्पुरुष श्रीगुलाबरावमहाराज यांचे चरित्र ",
      topic: "Biography",
      original: "",
    },
    {
      file: "marathi_ghatate_sartha_abhanga_gaatha",
      language: "Marathi",
      translator: "अनुवादक​: कृष्ण माधव घटाटे",
      author: "लेखक​: श्री गुलाबराव महाराज",
      series: "",
      title: "अभंग गाथा",
      extendedTitle: "मधुराद्वैताचार्य श्रीगुलाबराव महाराज विरचित सार्थ अभंग गाथा",
      topic: "Poetry",
      original: "",
    },
    {
      file: "marathi_gulabrao_maharaj_charitra_1",
      language: "Marathi",
      translator: "",
      author: "लेखक​: कृष्ण माधव घटाटे",
      series: "",
      title: "श्रीज्ञानेश्वरकन्यापदपांसु - १",
      extendedTitle: "वर्हाडातील सुप्रसिद्ध सत्पुरुष श्रीगुलाबरावमहाराज यांचे चरित्र ",
      topic: "Biography",
      original: "",
    },
    {
      file: "marathi_gulabrao_maharaj_charitra_2",
      language: "Marathi",
      translator: "",
      author: "लेखक​: कृष्ण माधव घटाटे",
      series: "",
      title: "श्रीज्ञानेश्वरकन्यापदपांसु - २",
      extendedTitle: "वर्हाडातील सुप्रसिद्ध सत्पुरुष श्रीगुलाबरावमहाराज यांचे चरित्र ",
      topic: "Biography",
      original: "",
    },
    {
      file: "marathi_jnyaneshwarancha_bhakti_vichaar",
      language: "Marathi",
      translator: "",
      author: "लेखक​: बाबाजी महाराज पंडित",
      series: "",
      title: "श्रीज्ञानेश्वरांचा भक्तिविचार",
      extendedTitle: "शंकरज्ञान-संयुक्तं, भगवद्भक्ति-अलंकृतं, यद्वाक्य् तत्प्रमाणं स्यात् ",
      topic: "Essay",
      original: "",
    },
    {
      file: "marathi_kanta_kanta_vakya_pushpam",
      language: "Marathi",
      translator: "अनुवादक​: बाबाजी महाराज पंडित",
      author: "लेखक​: श्री गुलाबराव महाराज",
      series: "",
      title: "कान्त कान्ता वाक्य पुष्पं",
      extendedTitle: "",
      topic: "Commentary",
      original: "",
    },
    {
      file: "marathi_naradiya_bhakti_sutra",
      language: "Marathi",
      translator: "अनुवादक​: बाबाजी महाराज पंडित",
      author: "लेखक​: श्री गुलाबराव महाराज",
      series: "",
      title: "नारदीय भक्ति सूत्र",
      extendedTitle: "मधुराद्वैताचार्य श्रीगुलाबराव महाराज कृत नारदीय भक्तिसूत्र भाष्य (उपासना आणि भक्ती) ",
      topic: "Commentary",
      original: "",
    },
    {
      file: "marathi_nitya_tirtha_alandi",
      language: "Marathi",
      translator: "अनुवादक​: बाबाजी महाराज पंडित",
      author: "लेखक​: श्री गुलाबराव महाराज",
      series: "",
      title: "नित्यतीर्थ",
      extendedTitle: "मराठी नित्यतीर्थ आळंदी महिमा ",
      topic: "",
      original: "",
    },
    {
      file: "marathi_panduranga_chausashthi",
      language: "Marathi",
      translator: "अनुवादक​: बाबाजी महाराज पंडित",
      author: "लेखक​: श्री गुलाबराव महाराज",
      series: "",
      title: "पांडुरंग चौसष्टी",
      extendedTitle: "अमृतानुभव प्रथम प्रकरणावरील श्रीगुलाबराव महाराअजंची पांडुरंग चौसष्टी",
      topic: "Commentary",
      original: "अमृतानुभव",
    },
    {
      file: "marathi_pativrata_charitamruta",
      language: "Marathi",
      translator: "अनुवादक​: बाबाजी महाराज पंडित",
      author: "लेखक​: श्री गुलाबराव महाराज",
      series: "",
      title: "पवित्रता चरितामृत ",
      extendedTitle: "मधुराद्वैताचार्य श्रीगुलाबराव महाराज विरचित १५ व्या यष्टीतील पतिव्रता चरितामृत ",
      topic: "",
      original: "",
    },
    {
      file: "marathi_patni_prema_parag",
      language: "Marathi",
      translator: "अनुवादक​: कृष्ण माधव घटाटे",
      author: "लेखक​: श्री गुलाबराव महाराज",
      series: "",
      title: "पत्नी प्रेम पराग ",
      extendedTitle: "मधुराद्वैताचर्य श्री गुलाबराव महाराजांचा पत्नी प्रेम पराग - प्रिय प्रेमोन्माद ",
      topic: "Commentary",
      original: "",
    },
    {
      file: "marathi_prajnya_chakshu_deepa_stambha",
      language: "Marathi",
      translator: "",
      author: "लेखक​: बाळ राणे",
      series: "",
      title: "प्रज्ञाचक्षुः दीपस्तंभ ",
      extendedTitle: "प्रज्ञाचक्षुः दीपस्तंभ - श्रीगुलाबराव महाराजांचे जीवन चरत्र",
      topic: "Biography",
      original: "",
    },
    {
      file: "marathi_pramada_kallola",
      language: "Marathi",
      translator: "",
      author: "लेखक​: श्री गुलाबराव महाराज",
      series: "",
      title: "प्रमादकल्लोळ",
      extendedTitle: "अपराध विचार - पामर उपासक ज्ञानी भक्त यांजकडून होणारे अपराध ",
      topic: "Commentary",
      original: "",
    },
    {
      file: "marathi_santa_katha",
      language: "Marathi",
      translator: "",
      author: "लेखक​: बाबाजी महाराज पंडित",
      series: "",
      title: "सन्त कथा",
      extendedTitle: "",
      topic: "",
      original: "",
    },
    {
      file: "marathi_shankar_tatvajnyaanaat_bhakti_che_sthaan",
      language: "Marathi",
      translator: "",
      author: "लेखक​: डाँ वा ना पंडित ",
      series: "",
      title: "शंकर तत्वज्ञानात भक्तीचे स्थान",
      extendedTitle: "",
      topic: "",
      original: "",
    },
    {
      file: "marathi_sookta_ratnavali",
      language: "Marathi",
      translator: "",
      author: "लेखक​: श्री गुलाबराव महाराज",
      series: "सूक्तरत्नावली",
      title: "द्वितीय यष्टी ",
      extendedTitle: "मधुराद्वैताचार्य श्रीगुलाबरावमहाराज विरचित सूक्तरत्नावली - द्वितीय यष्टी - उत्तरार्ध ",
      topic: "",
      original: "",
    },
    {
      file: "marathi_stree_geet_sangraha",
      language: "Marathi",
      translator: "",
      author: "लेखक​: श्री गुलाबराव महाराज",
      series: "सूक्तरत्नावली",
      title: "स्त्रीगीत संग्रह ",
      extendedTitle:
        "मधुराद्वैताचार्य श्रीगुलाबरावमहाराज विरचित सूक्तरत्नावली - चतुर्थ यष्टी - दळणकांडण करतेवेळीच्या आणी झोपाळ्यावरील वर्हाडी भाषेतील लोकगीतांचा संग्रह ",
      topic: "",
      original: "",
    },
    {
      file: "marathi_subodha_hindu_dharma",
      language: "Marathi",
      translator: "",
      author: "लेखक​: श्री गुलाबराव महाराज",
      series: "सूक्तरत्नावली",
      title: "गीता प्रवचने ",
      extendedTitle:
        "मधुराद्वैताचार्य श्रीगुलाबरावमहाराज विरचित सूक्तरत्नावली - सप्तदश यष्टी - समयोपदेश - सुबोध हिन्दू धर्म ",
      topic: "",
      original: "",
    },
    {
      file: "marathi_sukta_ratnavali_padanchi_gatha",
      language: "Marathi",
      translator: "",
      author: "लेखक​: श्री गुलाबराव महाराज",
      series: "सूक्तरत्नावली",
      title: "पदांची गाथा ",
      extendedTitle: "मधुराद्वैताचार्य श्रीगुलाबरावमहाराज विरचित सूक्तरत्नावली - नवम यष्टी - उत्तरार्ध ",
      topic: "",
      original: "",
    },
    {
      file: "marathi_sukta_ratnavali_prathama_yashti",
      language: "Marathi",
      translator: "",
      author: "लेखक​: श्री गुलाबराव महाराज",
      series: "सूक्तरत्नावली",
      title: "प्रथमयष्टी",
      extendedTitle: "मधुराद्वैताचार्य श्रीगुलाबरावमहाराज विरचित सूक्तरत्नावली - प्रथम यष्टी ",
      topic: "",
      original: "",
    },
    {
      file: "marathi_sukta_ratnavali_prema_nikunja",
      language: "Marathi",
      translator: "",
      author: "लेखक​: श्री गुलाबराव महाराज",
      series: "सूक्तरत्नावली",
      title: "प्रेमनिकुंज ",
      extendedTitle: "मधुराद्वैताचार्य श्रीगुलाबरावमहाराज विरचित सूक्तरत्नावली - दशम यष्टी ",
      topic: "",
      original: "",
    },
    {
      file: "marathi_sukta_ratnavali_priya_leela_mahotsava",
      language: "Marathi",
      translator: "",
      author: "लेखक​: श्री गुलाबराव महाराज",
      series: "सूक्तरत्नावली",
      title: "प्रियलीला महोत्सव ",
      extendedTitle:
        "मधुराद्वैताचार्य श्रीगुलाबरावमहाराज विरचित सूक्तरत्नावली - तृतीय यष्टी - प्रेमलीला महोत्सव - आमंत्रण विलास ",
      topic: "",
      original: "",
    },
    {
      file: "marathi_sukta_ratnavali_samayopadesha",
      language: "Marathi",
      translator: "",
      author: "लेखक​: श्री गुलाबराव महाराज",
      series: "सूक्तरत्नावली",
      title: "स्मयोपदेश ",
      extendedTitle: "मधुराद्वैताचार्य श्रीगुलाबरावमहाराज विरचित सूक्तरत्नावली - अठरावी यष्टी ",
      topic: "",
      original: "",
    },
    {
      file: "marathi_sukti_ratnavali_sadhubodha",
      language: "Marathi",
      translator: "",
      author: "लेखक​: श्री गुलाबराव महाराज",
      series: "सूक्तरत्नावली",
      title: "साधुबोध ",
      extendedTitle: "मधुराद्वैताचार्य श्रीगुलाबरावमहाराज विरचित सूक्तरत्नावली - अष्टम यष्टी ",
      topic: "",
      original: "",
    },
    {
      file: "marathi_svamata_nirnaya",
      language: "Marathi",
      translator: "",
      author: "लेखक​: श्री गुलाबराव महाराज",
      series: "सूक्तरत्नावली",
      title: "स्वमत निर्णय ",
      extendedTitle: "मधुराद्वैताचार्य श्रीगुलाबरावमहाराज विरचित सूक्तरत्नावली - सोळावी यष्टी ",
      topic: "",
      original: "",
    },
    {
      file: "marathi_vnpandit_adya_shankaracharya_bhakti_tatva",
      language: "Marathi",
      translator: "अनुवादक​: डाँ वा ना पंडित ",
      author: "लेखक​: श्री गुलाबराव महाराज",
      series: "",
      title: "आद्य शंकराचार्यांचे भक्तिस्तव ",
      extendedTitle: "",
      topic: "",
      original: "",
    },
    {
      file: "marathi_vnpandit_bhakti_tatva_vivek_para_bhakti",
      language: "Marathi",
      translator: "अनुवादक​: डाँ वा ना पंडित ",
      author: "लेखक​: श्री गुलाबराव महाराज",
      series: "",
      title: "भक्तितत्वविवेक",
      extendedTitle: "भक्तितत्वविवेक अर्थात पराभक्तिचे स्वरूप ",
      topic: "",
      original: "",
    },
    {
      file: "marathi_vnpandit_chiranjeeva_padabhyasa",
      language: "Marathi",
      translator: "अनुवादक​: डाँ वा ना पंडित ",
      author: "लेखक​: श्री गुलाबराव महाराज",
      series: "",
      title: "चिरंजीवपदाभ्यास ",
      extendedTitle: "मधुराद्वैताचार्य श्रीगुलाबरावमहाराज कृत भक्तिशास्त्र - चिरंजीव पदाभ्यास ",
      topic: "",
      original: "",
    },
    {
      file: "marathi_vnpandit_gulabrao_maharaj_vibhuti_ani_tatvajnyan",
      language: "Marathi",
      translator: "अनुवादक​: डाँ वा ना पंडित ",
      author: "लेखक​: श्री गुलाबराव महाराज",
      series: "",
      title: "विभूती आणि तत्वज्ञान ",
      extendedTitle: "श्रीगुलाबराव महाराज - विभूती आणि तत्वज्ञान ",
      topic: "",
      original: "",
    },
    {
      file: "marathi_vnpandit_jnyaneshwar_maharajanche_bhakti_darshan",
      language: "Marathi",
      translator: "अनुवादक​: डाँ वा ना पंडित ",
      author: "लेखक​: श्री गुलाबराव महाराज",
      series: "",
      title: "भक्तिदर्शन",
      extendedTitle: "श्री ज्ञानेश्वर महाराजांचे भक्ति दर्शन ",
      topic: "",
      original: "",
    },
    {
      file: "marathi_vnpandit_preeti_nartana_bhakti_mimamsa",
      language: "Marathi",
      translator: "अनुवादक​: डाँ वा ना पंडित ",
      author: "लेखक​: श्री गुलाबराव महाराज",
      series: "",
      title: "प्रीतिनर्तनः",
      extendedTitle: "मधुराद्वैताचार्य श्रीगुलाबरावमहाराज कृत प्रीतिनर्तनः - भक्ति मीमांसा ",
      topic: "",
      original: "",
    },
    {
      file: "marathi_vnpandit_tarkane_ishwar_siddhi",
      language: "Marathi",
      translator: "अनुवादक​: डाँ वा ना पंडित ",
      author: "लेखक​: श्री गुलाबराव महाराज",
      series: "",
      title: "तर्काने ईश्वरसिद्धी ",
      extendedTitle: "",
      topic: "",
      original: "",
    },
    {
      file: "marathi_yoga_prabhaava_patanjali_yoga_sutra",
      language: "Marathi",
      translator: "",
      author: "लेखक​: श्री गुलाबराव महाराज",
      series: "सूक्तरत्नावली",
      title: "योगप्रभाव ",
      extendedTitle:
        "मधुराद्वैताचार्य श्रीगुलाबरावमहाराज विरचित सूक्तरत्नावली - वीसावी यष्टी - योगप्रभाव - पतंजलि योग सूत्र ",
      topic: "",
      original: "पतंजलि योग सूत्र ",
    },
    {
      file: "marathi_yoga_rahasya",
      language: "Marathi",
      translator: "",
      author: "लेखक​: श्री गुलाबराव महाराज",
      series: "",
      title: "योगरहस्य ",
      extendedTitle: "मधुराद्वैताचार्य श्रीगुलाबरावमहाराज विरचित योगोपर दहा ग्रंथांचे संकलन ",
      topic: "",
      original: "",
    },
  ],
};
